# Generated by Django 3.0.1 on 2020-04-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jayapp', '0002_remove_user_cpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpassword',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
