# Generated by Django 3.0.1 on 2020-04-11 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jayapp', '0004_remove_user_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jayapp.User')),
            ],
        ),
    ]
