# Generated by Django 3.0.1 on 2020-04-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jayapp', '0005_todolistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
