# Generated by Django 3.0.1 on 2020-05-22 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jayapp', '0006_todolistitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
