# Generated by Django 3.0.1 on 2020-05-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jayapp', '0007_todolistitem_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='date_completed',
            field=models.DateTimeField(default=None),
        ),
    ]
