# Generated by Django 3.0.1 on 2020-05-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jayapp', '0008_todolistitem_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='date_completed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
